### PR TITLE
Fixed crash when using PFObject.deleteAll() with empty array.

### LINKED ISSUE #253: Calling deleteAll:error: on an empty array causes a crash
This will cause a crash :
```
dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0), ^{
	[PFObject deleteAll:@[] error:nil];
});
```
This is because `deleteAllInBackground:` returns a task whose result is not a boolean wrapped in an `NSNumber` when the array is empty.

### PR DESCRIPTION
**Pull request by nlutsenko**
- Fixed wrong return type for `deleteInBackground:` if objects array is empty.
- Added tests for all of this.
Fixes #253

### CODE REVIEW

File: Tests/Unit/ObjectUnitTests.m [hunk 1]
```diff
@@ -199,6 +200,30 @@ - (void)testFetchObjectWithoutObjectIdError {
...
+    XCTAssertTrue([PFObject deleteAll:nil]);
+    XCTAssertTrue([PFObject deleteAll:@[]]);
+
+    NSError *error = nil;
+    XCTAssertTrue([PFObject deleteAll:nil error:&error]);
+    XCTAssertNil(error);
+    XCTAssertTrue([PFObject deleteAll:@[] error:&error]);
+    XCTAssertNil(error);
+
+    XCTAssertTrue([[PFObject deleteAllInBackground:nil] waitForResult:nil]);
```
Comment (richardjrossiii) [inline Tests/Unit/ObjectUnitTests.m]: Don't use `XCTAssertTrue()` for object types.

Comment (nlutsenko) [inline Tests/Unit/ObjectUnitTests.m]: (－‸ლ)
