### PR TITLE
Fixed PFInstallation not updating automatic fields when using PFObject.saveAll().

### LINKED ISSUE #261: PFInstallation specific properties not set when calling [PFObject saveAllInBackground block]
My app sometimes saves an array of objects to Parse using [PFObject saveAllInBackground:objectsToSave block:^(BOOL succeeded, NSError *error)

This has been working fine, but since maybe a week or two some of the PFInstallation specific properties are not set. appIdentifier, appName, appVersion, badge, parseVersion, timeZone, localeIdentifier are all 'undefined'. All other properties are saved as expected. 

I solved this by calling [[PFInstallation currentDevice] saveInBackgroundWithBlock:^(BOOL succeeded, NSError *error) and now it works.

But this seems to be a bug. I tried rolling back to older versions of Parse iOS SDK but no change. So, possibly this is an issue server-side.

Thanks! Keep up the great work you are doing over at Parse :-)

### PR DESCRIPTION
**Pull request by nlutsenko**
Not coverable with unit tests just yet...

Fixes #261

### CODE REVIEW

File: Parse/Internal/Object/PFObjectPrivate.h [hunk 1]
```diff
@@ -58,6 +60,18 @@
...
 - (BFTask *)_validateSaveEventuallyAsync;
 
+@optional
+
+///--------------------------------------
+/// @name Before Save
+///--------------------------------------
+
+/*!
+ Called before an object is going to be safe. Called in a context of object lock.
```
Comment (richardjrossiii) [inline Parse/Internal/Object/PFObjectPrivate.h]: s/safe/saved/g.

File: Parse/PFInstallation.m [hunk 2]
```diff
@@ -257,7 +242,7 @@ - (BOOL)needsDefaultACL {
 #pragma mark - Automatic Info
 ///--------------------------------------
 
-- (void)_updateAutomaticInfo {
+- (void)_objectWillSave {
     if ([self _isCurrentInstallation]) {
         @synchronized(self.lock) {
```
Comment (richardjrossiii) [inline Parse/PFInstallation.m]: We already have the lock here, no need for it.
