### PR TITLE
Fix initialization of Facebook/Twitter Utils blocking the main thread.

### LINKED ISSUE #302: Parse iOS SDK 1.8.5 - App freezes on initializeFacebookWithApplicationLaunchOptions (iOS 9)
Hi!
I've faced with weird application freeze on the next launch after user logged in facebook using [PFFacebookUtils logInInBackgroundWithReadPermissions:]. I'm using xcode 7.0, iOS 9.0 and latest SDKs:
Installing Bolts (1.2.2)
Installing FBSDKCoreKit (4.6.0)
Installing FBSDKLoginKit (4.6.0)
Installing FBSDKShareKit (4.6.0)
Installing Parse (1.8.5)
Installing ParseFacebookUtilsV4 (1.8.5)
Also Info.plist updated according to App Transport Security policy.
Thanks for any info or help!
screenshot 2015-09-21 13 46 45

### PR DESCRIPTION
**Pull request by nlutsenko**
This will make load of currentUser asynchronous, as well as won't create anonymous user if enabled, and will properly restore auth from a background thread.
Fixes #302

### CODE REVIEW

File: Parse/Internal/User/AuthenticationProviders/Controller/PFUserAuthenticationController.m [hunk 1]
```diff
@@ -56,9 +57,11 @@ - (void)registerAuthenticationDelegate:(id<PFUserAuthenticationDelegate>)delegat
     });
 
     // TODO: (nlutsenko) Decouple this further.
-    if (![authType isEqualToString:PFAnonymousUserAuthenticationType]) {
-        [[PFUser currentUser] synchronizeAuthDataWithAuthType:authType];
-    }
+    [[[PFUser currentUserController] getCurrentUserAsyncWithOptions:0] continueWithSuccessBlock:^id(BFTask *task) {
```
Comment (richardjrossiii) [inline Parse/Internal/User/AuthenticationProviders/Controller/PFUserAuthenticationController.m]: How hard is it to have this injected? I don't really like having this be harder than necessary to test.

Comment (nlutsenko) [inline Parse/Internal/User/AuthenticationProviders/Controller/PFUserAuthenticationController.m]: Sure, let's do it. It's going to be much better.

**Comment by nlutsenko** [comment]
Injecting the currentUserController, all the way!
